# https://hub.docker.com/_/wordpress/
version: "3.1"
services:
  wordpress:
    depends_on:
      - database
    image: wordpress:5.5.3-apache
    restart: unless-stopped
    volumes:
      - ./data/wordpress:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 80:80
    networks:
      - backend

  database:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - database
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  backend: