# https://hub.docker.com/_/wordpress/
version: "3.1"
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  wordpress:
    depends_on:
      - database
    image: sigitasp/wp-with-plugins-dev:latest
    # build:
    #   context: ./wp-with-plugins-dev
    #   dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 80:80
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - database
    volumes: 
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./data/myadmin:/var/data
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 1024000kb
    networks:
      - backend

networks:
  backend: